"""create operational schema

Revision ID: 54038c26cea6
Revises:
Create Date: 2026-08-17 05:53:03.168878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54038c26cea6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_centre_reference',
    sa.Column('distribution_centre_id', sa.Uuid(), nullable=False),
    sa.Column('distribution_centre_code', sa.String(length=20), nullable=False),
    sa.Column('distribution_centre_name', sa.String(length=200), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('region_code', sa.String(length=20), nullable=False),
    sa.Column('location_area', sa.String(length=120), nullable=False),
    sa.Column('postcode_area', sa.String(length=12), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('supports_ambient', sa.Boolean(), nullable=False),
    sa.Column('supports_chilled', sa.Boolean(), nullable=False),
    sa.Column('supports_frozen', sa.Boolean(), nullable=False),
    sa.Column('daily_receiving_capacity_cases', sa.Integer(), nullable=False),
    sa.Column('daily_dispatch_capacity_cases', sa.Integer(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synchronised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('daily_dispatch_capacity_cases > 0', name=op.f('ck_distribution_centre_reference_daily_dispatch_capacity_positive')),
    sa.CheckConstraint('daily_receiving_capacity_cases > 0', name=op.f('ck_distribution_centre_reference_daily_receiving_capacity_positive')),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_distribution_centre_reference_latitude_range')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_distribution_centre_reference_longitude_range')),
    sa.PrimaryKeyConstraint('distribution_centre_id', name=op.f('pk_distribution_centre_reference')),
    sa.UniqueConstraint('distribution_centre_code', name='uq_distribution_centre_reference_distribution_centre_code')
    )
    with op.batch_alter_table('distribution_centre_reference', schema=None) as batch_op:
        batch_op.create_index('ix_distribution_centre_reference_active', ['active_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_centre_reference_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_distribution_centre_reference_region', ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_centre_reference_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_distribution_centre_reference_updated_id', ['updated_at', 'distribution_centre_id'], unique=False)

    op.create_table('product_reference',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory_code', sa.String(length=20), nullable=False),
    sa.Column('brand_type', sa.String(length=30), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('package_size', sa.String(length=60), nullable=False),
    sa.Column('case_pack_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('storage_type', sa.Enum('AMBIENT', 'CHILLED', 'FROZEN', name='product_storage_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('standard_retail_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_margin_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('safety_stock_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('demand_tier', sa.String(length=10), nullable=False),
    sa.Column('relative_demand_weight', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('country_of_origin', sa.String(length=2), nullable=False),
    sa.Column('origin_group', sa.String(length=30), nullable=False),
    sa.Column('perishable_flag', sa.Boolean(), nullable=False),
    sa.Column('age_restricted_flag', sa.Boolean(), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synchronised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('case_pack_quantity > 0', name=op.f('ck_product_reference_case_pack_quantity_positive')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_product_reference_effective_date_order')),
    sa.CheckConstraint('gross_margin_rate >= 0 AND gross_margin_rate <= 1', name=op.f('ck_product_reference_gross_margin_rate_range')),
    sa.CheckConstraint('relative_demand_weight > 0', name=op.f('ck_product_reference_relative_demand_weight_positive')),
    sa.CheckConstraint('reorder_level >= 0', name=op.f('ck_product_reference_reorder_level_non_negative')),
    sa.CheckConstraint('safety_stock_quantity >= 0', name=op.f('ck_product_reference_safety_stock_non_negative')),
    sa.CheckConstraint('shelf_life_days IS NULL OR shelf_life_days >= 0', name=op.f('ck_product_reference_shelf_life_days_non_negative')),
    sa.CheckConstraint('standard_retail_price >= 0', name=op.f('ck_product_reference_retail_price_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_product_reference_unit_cost_non_negative')),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 1', name=op.f('ck_product_reference_vat_rate_range')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product_reference')),
    sa.UniqueConstraint('product_code', name='uq_product_reference_product_code'),
    sa.UniqueConstraint('sku', name='uq_product_reference_sku')
    )
    with op.batch_alter_table('product_reference', schema=None) as batch_op:
        batch_op.create_index('ix_product_reference_category_subcategory', ['category_id', 'subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reference_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_product_reference_storage_active', ['storage_type', 'active_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reference_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_product_reference_updated_product', ['updated_at', 'product_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=250), nullable=False),
    sa.Column('supplier_type', sa.String(length=50), nullable=False),
    sa.Column('category_codes', sa.JSON(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('origin_group', sa.String(length=30), nullable=False),
    sa.Column('default_currency_code', sa.Enum('GBP', 'EUR', 'USD', 'AUD',name='currency_code', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('standard_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('minimum_order_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('supports_ambient', sa.Boolean(), nullable=False),
    sa.Column('supports_chilled', sa.Boolean(), nullable=False),
    sa.Column('supports_frozen', sa.Boolean(), nullable=False),
    sa.Column('risk_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='supplier_risk_rating', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('supplier_status', sa.Enum('PENDING', 'ACTIVE', 'ON_HOLD', 'SUSPENDED', 'INACTIVE', name='supplier_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('incoterm', sa.String(length=10), nullable=False),
    sa.Column('target_otif_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('target_quality_acceptance_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_suppliers_effective_date_order')),
    sa.CheckConstraint('minimum_order_value >= 0', name=op.f('ck_suppliers_minimum_order_value_non_negative')),
    sa.CheckConstraint('payment_terms_days >= 0', name=op.f('ck_suppliers_payment_terms_non_negative')),
    sa.CheckConstraint('standard_lead_time_days >= 0', name=op.f('ck_suppliers_standard_lead_time_non_negative')),
    sa.CheckConstraint('target_otif_rate >= 0 AND target_otif_rate <= 1', name=op.f('ck_suppliers_target_otif_rate_range')),
    sa.CheckConstraint('target_quality_acceptance_rate >= 0 AND target_quality_acceptance_rate <= 1', name=op.f('ck_suppliers_target_quality_acceptance_rate_range')),
    sa.PrimaryKeyConstraint('supplier_id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('contact_email', name='uq_suppliers_contact_email'),
    sa.UniqueConstraint('supplier_code', name='uq_suppliers_supplier_code')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_country_code', ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_suppliers_status_active', ['supplier_status', 'active_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_suppliers_updated_at_supplier_id', ['updated_at', 'supplier_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('distribution_centre_id', sa.Uuid(), nullable=False),
    sa.Column('distribution_centre_code', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('required_delivery_date', sa.Date(), nullable=False),
    sa.Column('order_type', sa.Enum('STANDARD_REPLENISHMENT', 'EMERGENCY_REPLENISHMENT', 'PROMOTIONAL', 'NEW_PRODUCT_LAUNCH', 'SEASONAL', name='purchase_order_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('purchase_order_status', sa.Enum('DRAFT', 'APPROVED', 'SUBMITTED', 'CONFIRMED', 'ACKNOWLEDGED', 'PARTIALLY_SHIPPED', 'DISPATCHED', 'SHIPPED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'COMPLETED', 'CLOSED', 'CANCELLED', name='purchase_order_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('currency_code', sa.Enum('GBP', 'EUR', 'USD', 'AUD',name='purchase_order_currency_code', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('total_net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_vat_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value_gbp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('buyer_code', sa.String(length=30), nullable=False),
    sa.Column('approval_role', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("(purchase_order_status = 'CANCELLED' AND cancellation_reason IS NOT NULL) OR (purchase_order_status <> 'CANCELLED')", name=op.f('ck_purchase_orders_cancelled_order_requires_reason')),
    sa.CheckConstraint('required_delivery_date >= order_date', name=op.f('ck_purchase_orders_required_delivery_not_before_order')),
    sa.CheckConstraint('ABS(total_gross_amount - (total_net_amount + total_vat_amount)) <= 0.01', name=op.f('ck_purchase_orders_header_amounts_reconcile')),
    sa.CheckConstraint('total_gross_amount >= 0', name=op.f('ck_purchase_orders_total_gross_amount_non_negative')),
    sa.CheckConstraint('total_net_amount >= 0', name=op.f('ck_purchase_orders_total_net_amount_non_negative')),
    sa.CheckConstraint('total_value_gbp >= 0', name=op.f('ck_purchase_orders_total_value_gbp_non_negative')),
    sa.CheckConstraint('total_vat_amount >= 0', name=op.f('ck_purchase_orders_total_vat_amount_non_negative')),
    sa.ForeignKeyConstraint(['distribution_centre_id'], ['distribution_centre_reference.distribution_centre_id'], name=op.f('fk_purchase_orders_distribution_centre_id_distribution_centre_reference'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('purchase_order_id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('purchase_order_number', name='uq_purchase_orders_purchase_order_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_purchase_orders_dc_delivery_date', ['distribution_centre_id', 'required_delivery_date'], unique=False)
        batch_op.create_index('ix_purchase_orders_order_date', ['order_date'], unique=False)
        batch_op.create_index('ix_purchase_orders_supplier_status', ['supplier_id', 'purchase_order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_purchase_orders_updated_id', ['updated_at', 'purchase_order_id'], unique=False)

    op.create_table('supplier_performance_monthly',
    sa.Column('supplier_performance_monthly_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('performance_month', sa.String(length=7), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('early_delivery_count', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_count', sa.Integer(), nullable=False),
    sa.Column('late_delivery_count', sa.Integer(), nullable=False),
    sa.Column('evaluated_purchase_order_count', sa.Integer(), nullable=False),
    sa.Column('otif_pass_count', sa.Integer(), nullable=False),
    sa.Column('otif_fail_count', sa.Integer(), nullable=False),
    sa.Column('in_full_pass_count', sa.Integer(), nullable=False),
    sa.Column('in_full_fail_count', sa.Integer(), nullable=False),
    sa.Column('total_received_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_damaged_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_rejected_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('temperature_controlled_delivery_count', sa.Integer(), nullable=False),
    sa.Column('temperature_breach_count', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('in_full_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('otif_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('accepted_quality_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('damage_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('rejection_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('temperature_compliance_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('performance_rating', sa.Enum('EXCELLENT', 'GOOD', 'WATCH', 'HIGH_RISK', 'ACCEPTABLE', 'NEEDS_IMPROVEMENT', 'POOR', name='supplier_performance_rating', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('risk_indicator', sa.Enum('NORMAL', 'WATCH', 'HIGH', 'CRITICAL', name='supplier_performance_risk_indicator', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("performance_month LIKE '____-__'", name=op.f('ck_supplier_performance_monthly_performance_month_format')),
    sa.CheckConstraint('accepted_quality_rate >= 0 AND accepted_quality_rate <= 1', name=op.f('ck_supplier_performance_monthly_accepted_quality_rate_range')),
    sa.CheckConstraint('damage_rate >= 0 AND damage_rate <= 1', name=op.f('ck_supplier_performance_monthly_damage_rate_range')),
    sa.CheckConstraint('delivery_count >= 0', name=op.f('ck_supplier_performance_monthly_delivery_count_non_negative')),
    sa.CheckConstraint('early_delivery_count + on_time_delivery_count + late_delivery_count = delivery_count', name=op.f('ck_supplier_performance_monthly_delivery_status_counts_reconcile')),
    sa.CheckConstraint('early_delivery_count >= 0 AND on_time_delivery_count >= 0 AND late_delivery_count >= 0', name=op.f('ck_supplier_performance_monthly_delivery_status_counts_non_negative')),
    sa.CheckConstraint('evaluated_purchase_order_count >= 0', name=op.f('ck_supplier_performance_monthly_evaluated_order_count_non_negative')),
    sa.CheckConstraint('in_full_pass_count + in_full_fail_count = evaluated_purchase_order_count', name=op.f('ck_supplier_performance_monthly_in_full_counts_reconcile')),
    sa.CheckConstraint('in_full_rate >= 0 AND in_full_rate <= 1', name=op.f('ck_supplier_performance_monthly_in_full_rate_range')),
    sa.CheckConstraint('on_time_delivery_rate >= 0 AND on_time_delivery_rate <= 1', name=op.f('ck_supplier_performance_monthly_on_time_delivery_rate_range')),
    sa.CheckConstraint('otif_pass_count + otif_fail_count = evaluated_purchase_order_count', name=op.f('ck_supplier_performance_monthly_otif_counts_reconcile')),
    sa.CheckConstraint('otif_pass_count >= 0 AND otif_fail_count >= 0 AND in_full_pass_count >= 0 AND in_full_fail_count >= 0', name=op.f('ck_supplier_performance_monthly_service_level_counts_non_negative')),
    sa.CheckConstraint('otif_rate >= 0 AND otif_rate <= 1', name=op.f('ck_supplier_performance_monthly_otif_rate_range')),
    sa.CheckConstraint('performance_score >= 0 AND performance_score <= 100', name=op.f('ck_supplier_performance_monthly_performance_score_range')),
    sa.CheckConstraint('rejection_rate >= 0 AND rejection_rate <= 1', name=op.f('ck_supplier_performance_monthly_rejection_rate_range')),
    sa.CheckConstraint('temperature_breach_count <= temperature_controlled_delivery_count', name=op.f('ck_supplier_performance_monthly_temperature_breaches_not_above_deliveries')),
    sa.CheckConstraint('temperature_compliance_rate >= 0 AND temperature_compliance_rate <= 1', name=op.f('ck_supplier_performance_monthly_temperature_compliance_rate_range')),
    sa.CheckConstraint('temperature_controlled_delivery_count >= 0 AND temperature_breach_count >= 0', name=op.f('ck_supplier_performance_monthly_temperature_counts_non_negative')),
    sa.CheckConstraint('total_received_quantity = total_accepted_quantity + total_damaged_quantity + total_rejected_quantity', name=op.f('ck_supplier_performance_monthly_quality_quantities_reconcile')),
    sa.CheckConstraint('total_received_quantity >= 0 AND total_accepted_quantity >= 0 AND total_damaged_quantity >= 0 AND total_rejected_quantity >= 0', name=op.f('ck_supplier_performance_monthly_quality_quantities_non_negative')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_performance_monthly_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_performance_monthly_id', name=op.f('pk_supplier_performance_monthly')),
    sa.UniqueConstraint('idempotency_key', name='uq_supplier_performance_monthly_idempotency_key'),
    sa.UniqueConstraint('supplier_id', 'performance_month', name='uq_supplier_performance_monthly_supplier_month')
    )
    with op.batch_alter_table('supplier_performance_monthly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_performance_monthly_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_supplier_performance_monthly_month_rating', ['performance_month', 'performance_rating'], unique=False)
        batch_op.create_index('ix_supplier_performance_monthly_risk', ['risk_indicator'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_performance_monthly_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_supplier_performance_monthly_updated_id', ['updated_at', 'supplier_performance_monthly_id'], unique=False)

    op.create_table('supplier_products',
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('supplier_product_code', sa.String(length=50), nullable=False),
    sa.Column('agreement_role', sa.Enum('PRIMARY', 'SECONDARY', name='agreement_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_primary_supplier', sa.Boolean(), nullable=False),
    sa.Column('agreement_status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'TERMINATED', name='agreement_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('agreement_currency_code', sa.Enum('GBP', 'EUR', 'USD', 'AUD',name='agreement_currency_code', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('base_unit_cost_gbp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('agreed_unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gbp_value_per_currency_unit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('minimum_order_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('order_multiple', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('agreed_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('minimum_remaining_shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("(agreement_role = 'PRIMARY' AND is_primary_supplier) OR (agreement_role = 'SECONDARY' AND NOT is_primary_supplier)", name=op.f('ck_supplier_products_agreement_role_primary_flag_consistent')),
    sa.CheckConstraint('agreed_lead_time_days >= 0', name=op.f('ck_supplier_products_agreed_lead_time_non_negative')),
    sa.CheckConstraint('agreed_unit_cost >= 0', name=op.f('ck_supplier_products_agreed_unit_cost_non_negative')),
    sa.CheckConstraint('base_unit_cost_gbp >= 0', name=op.f('ck_supplier_products_base_unit_cost_gbp_non_negative')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_supplier_products_effective_date_order')),
    sa.CheckConstraint('gbp_value_per_currency_unit > 0', name=op.f('ck_supplier_products_currency_conversion_rate_positive')),
    sa.CheckConstraint('minimum_order_quantity > 0', name=op.f('ck_supplier_products_minimum_order_quantity_positive')),
    sa.CheckConstraint('minimum_remaining_shelf_life_days >= 0', name=op.f('ck_supplier_products_minimum_shelf_life_non_negative')),
    sa.CheckConstraint('order_multiple > 0', name=op.f('ck_supplier_products_order_multiple_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['product_reference.product_id'], name=op.f('fk_supplier_products_product_id_product_reference'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_products_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_product_id', name=op.f('pk_supplier_products')),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_products_supplier_product'),
    sa.UniqueConstraint('supplier_product_code', name='uq_supplier_products_supplier_product_code')
    )
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_supplier_products_primary_product', ['product_id', 'is_primary_supplier'], unique=False)
        batch_op.create_index('ix_supplier_products_product_status', ['product_id', 'agreement_status'], unique=False)
        batch_op.create_index('ix_supplier_products_supplier_status', ['supplier_id', 'agreement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_products_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_supplier_products_updated_id', ['updated_at', 'supplier_product_id'], unique=False)

    op.create_table('supplier_status_history',
    sa.Column('supplier_status_history_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'ACTIVE', 'ON_HOLD', 'SUSPENDED', 'INACTIVE', name='supplier_previous_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'ACTIVE', 'ON_HOLD', 'SUSPENDED', 'INACTIVE', name='supplier_new_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('previous_status IS NULL OR previous_status <> new_status', name=op.f('ck_supplier_status_history_status_must_change')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_status_history_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_status_history_id', name=op.f('pk_supplier_status_history'))
    )
    with op.batch_alter_table('supplier_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_supplier_status_history_supplier_occurred', ['supplier_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_status_history_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_supplier_status_history_updated_id', ['updated_at', 'supplier_status_history_id'], unique=False)

    op.create_table('purchase_order_lines',
    sa.Column('purchase_order_line_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=30), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('order_multiple', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.Enum('GBP', 'EUR', 'USD', 'AUD',name='purchase_order_line_currency_code', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('ABS(gross_amount - (net_amount + vat_amount)) <= 0.01', name=op.f('ck_purchase_order_lines_line_amounts_reconcile')),
    sa.CheckConstraint('gross_amount >= 0', name=op.f('ck_purchase_order_lines_gross_amount_non_negative')),
    sa.CheckConstraint('line_number > 0', name=op.f('ck_purchase_order_lines_line_number_positive')),
    sa.CheckConstraint('net_amount >= 0', name=op.f('ck_purchase_order_lines_net_amount_non_negative')),
    sa.CheckConstraint('order_multiple > 0', name=op.f('ck_purchase_order_lines_order_multiple_positive')),
    sa.CheckConstraint('ordered_quantity > 0', name=op.f('ck_purchase_order_lines_ordered_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_purchase_order_lines_unit_price_non_negative')),
    sa.CheckConstraint('vat_amount >= 0', name=op.f('ck_purchase_order_lines_vat_amount_non_negative')),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 1', name=op.f('ck_purchase_order_lines_vat_rate_range')),
    sa.ForeignKeyConstraint(['product_id'], ['product_reference.product_id'], name=op.f('fk_purchase_order_lines_product_id_product_reference'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.purchase_order_id'], name=op.f('fk_purchase_order_lines_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.supplier_product_id'], name=op.f('fk_purchase_order_lines_supplier_product_id_supplier_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('purchase_order_line_id', name=op.f('pk_purchase_order_lines')),
    sa.UniqueConstraint('purchase_order_id', 'line_number', name='uq_purchase_order_lines_order_line'),
    sa.UniqueConstraint('purchase_order_id', 'product_id', name='uq_purchase_order_lines_order_product')
    )
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_purchase_order_lines_order', ['purchase_order_id'], unique=False)
        batch_op.create_index('ix_purchase_order_lines_product', ['product_id'], unique=False)
        batch_op.create_index('ix_purchase_order_lines_supplier_product', ['supplier_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_purchase_order_lines_updated_id', ['updated_at', 'purchase_order_line_id'], unique=False)

    op.create_table('shipments',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_shipment_reference', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('distribution_centre_id', sa.Uuid(), nullable=False),
    sa.Column('distribution_centre_code', sa.String(length=20), nullable=False),
    sa.Column('carrier_code', sa.String(length=30), nullable=False),
    sa.Column('carrier_name', sa.String(length=150), nullable=False),
    sa.Column('vehicle_type', sa.String(length=40), nullable=False),
    sa.Column('shipment_status', sa.Enum('PLANNED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'IN_TRANSIT', 'DELAYED', 'ARRIVED', 'DELIVERED', 'CANCELLED', name='shipment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('delivery_performance_status', sa.Enum('EARLY', 'ON_TIME', 'LATE', 'NOT_EVALUATED', 'NOT_APPLICABLE', name='delivery_performance_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('planned_dispatch_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_dispatch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_planned_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_shipped_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_received_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_damaged_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_rejected_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('temperature_controlled_flag', sa.Boolean(), nullable=False),
    sa.Column('minimum_recorded_temperature_celsius', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('maximum_recorded_temperature_celsius', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('temperature_breach_flag', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("(shipment_status = 'CANCELLED' AND cancellation_reason IS NOT NULL) OR (shipment_status <> 'CANCELLED')", name=op.f('ck_shipments_cancelled_shipment_requires_reason')),
    sa.CheckConstraint('(NOT temperature_controlled_flag AND minimum_recorded_temperature_celsius IS NULL AND maximum_recorded_temperature_celsius IS NULL AND NOT temperature_breach_flag) OR temperature_controlled_flag', name=op.f('ck_shipments_temperature_fields_consistent')),
    sa.CheckConstraint('actual_delivery_at IS NULL OR actual_dispatch_at IS NULL OR actual_delivery_at >= actual_dispatch_at', name=op.f('ck_shipments_actual_delivery_after_dispatch')),
    sa.CheckConstraint('actual_dispatch_at IS NULL OR actual_dispatch_at >= planned_dispatch_at', name=op.f('ck_shipments_actual_dispatch_after_planned_dispatch')),
    sa.CheckConstraint('expected_delivery_at >= planned_dispatch_at', name=op.f('ck_shipments_expected_delivery_after_planned_dispatch')),
    sa.CheckConstraint('minimum_recorded_temperature_celsius IS NULL OR maximum_recorded_temperature_celsius IS NULL OR minimum_recorded_temperature_celsius <= maximum_recorded_temperature_celsius', name=op.f('ck_shipments_temperature_range_order')),
    sa.CheckConstraint('total_accepted_quantity >= 0', name=op.f('ck_shipments_total_accepted_quantity_non_negative')),
    sa.CheckConstraint('total_damaged_quantity >= 0', name=op.f('ck_shipments_total_damaged_quantity_non_negative')),
    sa.CheckConstraint('total_planned_quantity >= 0', name=op.f('ck_shipments_total_planned_quantity_non_negative')),
    sa.CheckConstraint('total_received_quantity <= total_shipped_quantity', name=op.f('ck_shipments_received_not_above_shipped')),
    sa.CheckConstraint('total_received_quantity = total_accepted_quantity + total_damaged_quantity + total_rejected_quantity', name=op.f('ck_shipments_received_quantity_reconciles')),
    sa.CheckConstraint('total_received_quantity >= 0', name=op.f('ck_shipments_total_received_quantity_non_negative')),
    sa.CheckConstraint('total_rejected_quantity >= 0', name=op.f('ck_shipments_total_rejected_quantity_non_negative')),
    sa.CheckConstraint('total_shipped_quantity <= total_planned_quantity', name=op.f('ck_shipments_shipped_not_above_planned')),
    sa.CheckConstraint('total_shipped_quantity >= 0', name=op.f('ck_shipments_total_shipped_quantity_non_negative')),
    sa.ForeignKeyConstraint(['distribution_centre_id'], ['distribution_centre_reference.distribution_centre_id'], name=op.f('fk_shipments_distribution_centre_id_distribution_centre_reference'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.purchase_order_id'], name=op.f('fk_shipments_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_shipments_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('shipment_id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('shipment_number', name='uq_shipments_shipment_number'),
    sa.UniqueConstraint('supplier_shipment_reference', name='uq_shipments_supplier_shipment_reference')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index('ix_shipments_actual_delivery', ['actual_delivery_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_shipments_dc_expected_delivery', ['distribution_centre_id', 'expected_delivery_at'], unique=False)
        batch_op.create_index('ix_shipments_purchase_order', ['purchase_order_id'], unique=False)
        batch_op.create_index('ix_shipments_supplier_status', ['supplier_id', 'shipment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_shipments_updated_id', ['updated_at', 'shipment_id'], unique=False)

    op.create_table('shipment_lines',
    sa.Column('shipment_line_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_number', sa.String(length=30), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=30), nullable=False),
    sa.Column('purchase_order_line_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('storage_type', sa.Enum('AMBIENT', 'CHILLED', 'FROZEN', name='shipment_line_storage_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('order_multiple', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('shipped_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('damaged_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('accepted_quantity >= 0', name=op.f('ck_shipment_lines_accepted_quantity_non_negative')),
    sa.CheckConstraint('damaged_quantity >= 0', name=op.f('ck_shipment_lines_damaged_quantity_non_negative')),
    sa.CheckConstraint('line_number > 0', name=op.f('ck_shipment_lines_line_number_positive')),
    sa.CheckConstraint('order_multiple > 0', name=op.f('ck_shipment_lines_order_multiple_positive')),
    sa.CheckConstraint('ordered_quantity > 0', name=op.f('ck_shipment_lines_ordered_quantity_positive')),
    sa.CheckConstraint('planned_quantity <= ordered_quantity', name=op.f('ck_shipment_lines_planned_not_above_ordered')),
    sa.CheckConstraint('planned_quantity > 0', name=op.f('ck_shipment_lines_planned_quantity_positive')),
    sa.CheckConstraint('received_quantity <= shipped_quantity', name=op.f('ck_shipment_lines_received_not_above_shipped')),
    sa.CheckConstraint('received_quantity = accepted_quantity + damaged_quantity + rejected_quantity', name=op.f('ck_shipment_lines_received_quantity_reconciles')),
    sa.CheckConstraint('received_quantity >= 0', name=op.f('ck_shipment_lines_received_quantity_non_negative')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_shipment_lines_rejected_quantity_non_negative')),
    sa.CheckConstraint('shipped_quantity <= planned_quantity', name=op.f('ck_shipment_lines_shipped_not_above_planned')),
    sa.CheckConstraint('shipped_quantity >= 0', name=op.f('ck_shipment_lines_shipped_quantity_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['product_reference.product_id'], name=op.f('fk_shipment_lines_product_id_product_reference'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.purchase_order_id'], name=op.f('fk_shipment_lines_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.purchase_order_line_id'], name=op.f('fk_shipment_lines_purchase_order_line_id_purchase_order_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], name=op.f('fk_shipment_lines_shipment_id_shipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.supplier_product_id'], name=op.f('fk_shipment_lines_supplier_product_id_supplier_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('shipment_line_id', name=op.f('pk_shipment_lines')),
    sa.UniqueConstraint('shipment_id', 'purchase_order_line_id', name='uq_shipment_lines_shipment_order_line')
    )
    with op.batch_alter_table('shipment_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_lines_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_shipment_lines_order_line', ['purchase_order_line_id'], unique=False)
        batch_op.create_index('ix_shipment_lines_product', ['product_id'], unique=False)
        batch_op.create_index('ix_shipment_lines_shipment', ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_lines_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_shipment_lines_updated_id', ['updated_at', 'shipment_line_id'], unique=False)

    op.create_table('shipment_status_history',
    sa.Column('shipment_status_history_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_number', sa.String(length=30), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('PLANNED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'IN_TRANSIT', 'DELAYED', 'ARRIVED', 'DELIVERED', 'CANCELLED', name='shipment_previous_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('new_status', sa.Enum('PLANNED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'IN_TRANSIT', 'DELAYED', 'ARRIVED', 'DELIVERED', 'CANCELLED', name='shipment_new_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('previous_status IS NULL OR previous_status <> new_status', name=op.f('ck_shipment_status_history_status_must_change')),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_shipment_status_history_sequence_number_positive')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], name=op.f('fk_shipment_status_history_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipment_status_history_id', name=op.f('pk_shipment_status_history')),
    sa.UniqueConstraint('shipment_id', 'sequence_number', name='uq_shipment_status_history_shipment_sequence')
    )
    with op.batch_alter_table('shipment_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_shipment_status_history_created_id', ['created_at', 'shipment_status_history_id'], unique=False)
        batch_op.create_index('ix_shipment_status_history_shipment_changed', ['shipment_id', 'status_changed_at'], unique=False)

    op.create_table('supplier_performance_events',
    sa.Column('supplier_performance_event_id', sa.Uuid(), nullable=False),
    sa.Column('event_number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_category', sa.Enum('DELIVERY', 'QUALITY', 'COLD_CHAIN', 'SERVICE_LEVEL', 'IN_FULL', 'OTIF', 'TEMPERATURE', 'COMPLIANCE', name='performance_event_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', 'INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', name='performance_event_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('shipment_number', sa.String(length=30), nullable=True),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_order_number', sa.String(length=30), nullable=True),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('goods_receipt_number', sa.String(length=30), nullable=True),
    sa.Column('event_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performance_month', sa.String(length=7), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('metric_actual_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('metric_target_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('passed_flag', sa.Boolean(), nullable=False),
    sa.Column('score_impact', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("performance_month LIKE '____-__'", name=op.f('ck_supplier_performance_events_performance_month_format')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.purchase_order_id'], name=op.f('fk_supplier_performance_events_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], name=op.f('fk_supplier_performance_events_shipment_id_shipments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_performance_events_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_performance_event_id', name=op.f('pk_supplier_performance_events')),
    sa.UniqueConstraint('event_number', name='uq_supplier_performance_events_event_number'),
    sa.UniqueConstraint('idempotency_key', name='uq_supplier_performance_events_idempotency_key')
    )
    with op.batch_alter_table('supplier_performance_events', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_performance_events_category_time', ['event_category', 'event_occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_performance_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_supplier_performance_events_goods_receipt', ['goods_receipt_id'], unique=False)
        batch_op.create_index('ix_supplier_performance_events_purchase_order', ['purchase_order_id'], unique=False)
        batch_op.create_index('ix_supplier_performance_events_shipment', ['shipment_id'], unique=False)
        batch_op.create_index('ix_supplier_performance_events_supplier_month', ['supplier_id', 'performance_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_performance_events_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index('ix_supplier_performance_events_updated_id', ['updated_at', 'supplier_performance_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_performance_events', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_performance_events_updated_id')
        batch_op.drop_index(batch_op.f('ix_supplier_performance_events_updated_at'))
        batch_op.drop_index('ix_supplier_performance_events_supplier_month')
        batch_op.drop_index('ix_supplier_performance_events_shipment')
        batch_op.drop_index('ix_supplier_performance_events_purchase_order')
        batch_op.drop_index('ix_supplier_performance_events_goods_receipt')
        batch_op.drop_index(batch_op.f('ix_supplier_performance_events_created_at'))
        batch_op.drop_index('ix_supplier_performance_events_category_time')

    op.drop_table('supplier_performance_events')
    with op.batch_alter_table('shipment_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_shipment_status_history_shipment_changed')
        batch_op.drop_index('ix_shipment_status_history_created_id')

    op.drop_table('shipment_status_history')
    with op.batch_alter_table('shipment_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_shipment_lines_updated_id')
        batch_op.drop_index(batch_op.f('ix_shipment_lines_updated_at'))
        batch_op.drop_index('ix_shipment_lines_shipment')
        batch_op.drop_index('ix_shipment_lines_product')
        batch_op.drop_index('ix_shipment_lines_order_line')
        batch_op.drop_index(batch_op.f('ix_shipment_lines_created_at'))

    op.drop_table('shipment_lines')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index('ix_shipments_updated_id')
        batch_op.drop_index(batch_op.f('ix_shipments_updated_at'))
        batch_op.drop_index('ix_shipments_supplier_status')
        batch_op.drop_index('ix_shipments_purchase_order')
        batch_op.drop_index('ix_shipments_dc_expected_delivery')
        batch_op.drop_index(batch_op.f('ix_shipments_created_at'))
        batch_op.drop_index('ix_shipments_actual_delivery')

    op.drop_table('shipments')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_order_lines_updated_id')
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_updated_at'))
        batch_op.drop_index('ix_purchase_order_lines_supplier_product')
        batch_op.drop_index('ix_purchase_order_lines_product')
        batch_op.drop_index('ix_purchase_order_lines_order')
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_created_at'))

    op.drop_table('purchase_order_lines')
    with op.batch_alter_table('supplier_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_status_history_updated_id')
        batch_op.drop_index(batch_op.f('ix_supplier_status_history_updated_at'))
        batch_op.drop_index('ix_supplier_status_history_supplier_occurred')
        batch_op.drop_index(batch_op.f('ix_supplier_status_history_created_at'))

    op.drop_table('supplier_status_history')
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_products_updated_id')
        batch_op.drop_index(batch_op.f('ix_supplier_products_updated_at'))
        batch_op.drop_index('ix_supplier_products_supplier_status')
        batch_op.drop_index('ix_supplier_products_product_status')
        batch_op.drop_index('ix_supplier_products_primary_product')
        batch_op.drop_index(batch_op.f('ix_supplier_products_created_at'))

    op.drop_table('supplier_products')
    with op.batch_alter_table('supplier_performance_monthly', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_performance_monthly_updated_id')
        batch_op.drop_index(batch_op.f('ix_supplier_performance_monthly_updated_at'))
        batch_op.drop_index('ix_supplier_performance_monthly_risk')
        batch_op.drop_index('ix_supplier_performance_monthly_month_rating')
        batch_op.drop_index(batch_op.f('ix_supplier_performance_monthly_created_at'))

    op.drop_table('supplier_performance_monthly')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_orders_updated_id')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_updated_at'))
        batch_op.drop_index('ix_purchase_orders_supplier_status')
        batch_op.drop_index('ix_purchase_orders_order_date')
        batch_op.drop_index('ix_purchase_orders_dc_delivery_date')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_created_at'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('ix_suppliers_updated_at_supplier_id')
        batch_op.drop_index(batch_op.f('ix_suppliers_updated_at'))
        batch_op.drop_index('ix_suppliers_status_active')
        batch_op.drop_index(batch_op.f('ix_suppliers_created_at'))
        batch_op.drop_index('ix_suppliers_country_code')

    op.drop_table('suppliers')
    with op.batch_alter_table('product_reference', schema=None) as batch_op:
        batch_op.drop_index('ix_product_reference_updated_product')
        batch_op.drop_index(batch_op.f('ix_product_reference_updated_at'))
        batch_op.drop_index('ix_product_reference_storage_active')
        batch_op.drop_index(batch_op.f('ix_product_reference_created_at'))
        batch_op.drop_index('ix_product_reference_category_subcategory')

    op.drop_table('product_reference')
    with op.batch_alter_table('distribution_centre_reference', schema=None) as batch_op:
        batch_op.drop_index('ix_distribution_centre_reference_updated_id')
        batch_op.drop_index(batch_op.f('ix_distribution_centre_reference_updated_at'))
        batch_op.drop_index('ix_distribution_centre_reference_region')
        batch_op.drop_index(batch_op.f('ix_distribution_centre_reference_created_at'))
        batch_op.drop_index('ix_distribution_centre_reference_active')

    op.drop_table('distribution_centre_reference')
    # ### end Alembic commands ###
